# Generated by Django 5.1.2 on 2025-05-17 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapplication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panne',
            name='maintenancier',
        ),
        migrations.AlterField(
            model_name='panne',
            name='agent_commercial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monapplication.agentcommercial'),
        ),
        migrations.DeleteModel(
            name='Equipement',
        ),
    ]
