# Generated by Django 5.1.2 on 2025-05-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapplication', '0002_remove_panne_maintenancier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='panne',
            name='type_equipement',
            field=models.CharField(choices=[('TERMINAL', 'Terminal'), ('IMPRIMANTE', 'Imprimante'), ('CHARGEUR', 'Chargeur'), ('ECD', 'ECD')], default='ECD', max_length=50),
            preserve_default=False,
        ),
    ]
