# Generated by Django 5.1.2 on 2025-05-19 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapplication', '0003_panne_type_equipement'),
    ]

    operations = [
        migrations.AddField(
            model_name='panne',
            name='etat',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('RESOLUE', 'Résolue')], default='EN_ATTENTE', max_length=20),
        ),
    ]
