# Generated by Django 5.1.2 on 2025-05-19 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapplication', '0004_panne_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentcommercial',
            name='gerant',
            field=models.ForeignKey(blank=True, limit_choices_to={'gerant_de_club': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='monapplication.agentcommercial'),
        ),
        migrations.AlterField(
            model_name='panne',
            name='etat',
            field=models.CharField(choices=[('en_attente', 'en_attente'), ('resolue', 'resolue')], default='en_attente', max_length=20),
        ),
    ]
