# Generated by Django 5.1.2 on 2025-05-19 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapplication', '0005_agentcommercial_gerant_alter_panne_etat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agence',
            name='localisation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agentcommercial',
            name='gerant',
            field=models.ForeignKey(blank=True, limit_choices_to={'gerant_de_club': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents_sous_gerance', to='monapplication.agentcommercial', verbose_name='Gérant'),
        ),
        migrations.CreateModel(
            name='ResponsableAgence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=10, unique=True)),
                ('telephone', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='agence',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monapplication.responsableagence', verbose_name="Responsable de l'agence"),
        ),
    ]
