# Generated by Django 5.1.2 on 2025-05-19 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monapplication', '0006_agence_localisation_alter_agentcommercial_gerant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agence',
            name='telephone',
        ),
    ]
