# Generated by Django 5.1.2 on 2025-05-19 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapplication', '0007_remove_agence_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanneAgence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('est_resolue', models.BooleanField(default=False)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('vue_par_admin', models.BooleanField(default=False)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monapplication.agence')),
                ('maintenanciers', models.ManyToManyField(blank=True, to='monapplication.agent')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monapplication.responsableagence')),
            ],
        ),
    ]
