# Generated by Django 5.1.2 on 2025-05-20 00:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapplication', '0008_panneagence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('panne_signalee', 'Panne signalée'), ('panne_resolue', 'Panne résolue')], max_length=50)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='panneagence',
            name='date_resolution',
        ),
        migrations.RemoveField(
            model_name='panneagence',
            name='est_resolue',
        ),
        migrations.RemoveField(
            model_name='panneagence',
            name='vue_par_admin',
        ),
        migrations.AddField(
            model_name='panneagence',
            name='etat',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('resolue', 'Résolue')], default='en_attente', max_length=20),
        ),
        migrations.AddField(
            model_name='panneagence',
            name='titre',
            field=models.CharField(default='Panne', max_length=255),
        ),
        migrations.AlterField(
            model_name='panneagence',
            name='date_signalement',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
