# Generated by Django 5.1.2 on 2025-05-21 12:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapplication', '0009_notification_remove_panneagence_date_resolution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
        migrations.AddField(
            model_name='notification',
            name='panne_agence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monapplication.panneagence'),
        ),
        migrations.AddField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(default='panne', max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='VisiteMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visite', models.DateField()),
                ('objet', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monapplication.agence')),
            ],
        ),
    ]
