# Generated by Django 5.1.2 on 2025-05-27 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapplication', '0010_remove_notification_type_notification_panne_agence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='panne',
            name='maintenancier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='monapplication.agent'),
            preserve_default=False,
        ),
    ]
