# Generated by Django 5.1.2 on 2025-05-27 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapplication', '0011_panne_maintenancier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panne',
            name='maintenancier',
        ),
        migrations.AlterField(
            model_name='panne',
            name='etat',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('resolue', 'Résolue')], default='en_attente', max_length=20),
        ),
    ]
