# Generated by Django 5.1.2 on 2025-05-27 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapplication', '0012_remove_panne_maintenancier_alter_panne_etat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='panne',
            name='maintenancier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pannes_signalees', to=settings.AUTH_USER_MODEL),
        ),
    ]
